execute if score @s CurrentFrame matches 0 run function keyboard:show_frame10
execute if score @s CurrentFrame matches 1 run function keyboard:show_frame0
execute if score @s CurrentFrame matches 2 run function keyboard:show_frame1
execute if score @s CurrentFrame matches 3 run function keyboard:show_frame2
execute if score @s CurrentFrame matches 4 run function keyboard:show_frame3
execute if score @s CurrentFrame matches 5 run function keyboard:show_frame4
execute if score @s CurrentFrame matches 6 run function keyboard:show_frame5
execute if score @s CurrentFrame matches 7 run function keyboard:show_frame6
execute if score @s CurrentFrame matches 8 run function keyboard:show_frame7
execute if score @s CurrentFrame matches 9 run function keyboard:show_frame8
execute if score @s CurrentFrame matches 10 run function keyboard:show_frame9