summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char0"]}
scoreboard players set @e[tag=keyboard.char0] Keyboard.Index 0
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char1"]}
scoreboard players set @e[tag=keyboard.char1] Keyboard.Index 1
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char2"]}
scoreboard players set @e[tag=keyboard.char2] Keyboard.Index 2
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char3"]}
scoreboard players set @e[tag=keyboard.char3] Keyboard.Index 3
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char4"]}
scoreboard players set @e[tag=keyboard.char4] Keyboard.Index 4
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char5"]}
scoreboard players set @e[tag=keyboard.char5] Keyboard.Index 5
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char6"]}
scoreboard players set @e[tag=keyboard.char6] Keyboard.Index 6
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char7"]}
scoreboard players set @e[tag=keyboard.char7] Keyboard.Index 7
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char8"]}
scoreboard players set @e[tag=keyboard.char8] Keyboard.Index 8
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char9"]}
scoreboard players set @e[tag=keyboard.char9] Keyboard.Index 9
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char10"]}
scoreboard players set @e[tag=keyboard.char10] Keyboard.Index 10
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char11"]}
scoreboard players set @e[tag=keyboard.char11] Keyboard.Index 11
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char12"]}
scoreboard players set @e[tag=keyboard.char12] Keyboard.Index 12
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char13"]}
scoreboard players set @e[tag=keyboard.char13] Keyboard.Index 13
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char14"]}
scoreboard players set @e[tag=keyboard.char14] Keyboard.Index 14
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char15"]}
scoreboard players set @e[tag=keyboard.char15] Keyboard.Index 15
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char16"]}
scoreboard players set @e[tag=keyboard.char16] Keyboard.Index 16
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char17"]}
scoreboard players set @e[tag=keyboard.char17] Keyboard.Index 17
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char18"]}
scoreboard players set @e[tag=keyboard.char18] Keyboard.Index 18
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char19"]}
scoreboard players set @e[tag=keyboard.char19] Keyboard.Index 19
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char20"]}
scoreboard players set @e[tag=keyboard.char20] Keyboard.Index 20
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char21"]}
scoreboard players set @e[tag=keyboard.char21] Keyboard.Index 21
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char22"]}
scoreboard players set @e[tag=keyboard.char22] Keyboard.Index 22
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char23"]}
scoreboard players set @e[tag=keyboard.char23] Keyboard.Index 23
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char24"]}
scoreboard players set @e[tag=keyboard.char24] Keyboard.Index 24
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char25"]}
scoreboard players set @e[tag=keyboard.char25] Keyboard.Index 25
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char26"]}
scoreboard players set @e[tag=keyboard.char26] Keyboard.Index 26
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char27"]}
scoreboard players set @e[tag=keyboard.char27] Keyboard.Index 27
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char28"]}
scoreboard players set @e[tag=keyboard.char28] Keyboard.Index 28
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char29"]}
scoreboard players set @e[tag=keyboard.char29] Keyboard.Index 29
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char30"]}
scoreboard players set @e[tag=keyboard.char30] Keyboard.Index 30
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char31"]}
scoreboard players set @e[tag=keyboard.char31] Keyboard.Index 31
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char32"]}
scoreboard players set @e[tag=keyboard.char32] Keyboard.Index 32
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char33"]}
scoreboard players set @e[tag=keyboard.char33] Keyboard.Index 33
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char34"]}
scoreboard players set @e[tag=keyboard.char34] Keyboard.Index 34
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char35"]}
scoreboard players set @e[tag=keyboard.char35] Keyboard.Index 35
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char36"]}
scoreboard players set @e[tag=keyboard.char36] Keyboard.Index 36
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char37"]}
scoreboard players set @e[tag=keyboard.char37] Keyboard.Index 37
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char38"]}
scoreboard players set @e[tag=keyboard.char38] Keyboard.Index 38
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char39"]}
scoreboard players set @e[tag=keyboard.char39] Keyboard.Index 39
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char40"]}
scoreboard players set @e[tag=keyboard.char40] Keyboard.Index 40
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char41"]}
scoreboard players set @e[tag=keyboard.char41] Keyboard.Index 41
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char42"]}
scoreboard players set @e[tag=keyboard.char42] Keyboard.Index 42
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char43"]}
scoreboard players set @e[tag=keyboard.char43] Keyboard.Index 43
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char44"]}
scoreboard players set @e[tag=keyboard.char44] Keyboard.Index 44
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char45"]}
scoreboard players set @e[tag=keyboard.char45] Keyboard.Index 45
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char46"]}
scoreboard players set @e[tag=keyboard.char46] Keyboard.Index 46
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char47"]}
scoreboard players set @e[tag=keyboard.char47] Keyboard.Index 47
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char48"]}
scoreboard players set @e[tag=keyboard.char48] Keyboard.Index 48
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char49"]}
scoreboard players set @e[tag=keyboard.char49] Keyboard.Index 49
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char50"]}
scoreboard players set @e[tag=keyboard.char50] Keyboard.Index 50
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char51"]}
scoreboard players set @e[tag=keyboard.char51] Keyboard.Index 51
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char52"]}
scoreboard players set @e[tag=keyboard.char52] Keyboard.Index 52
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char53"]}
scoreboard players set @e[tag=keyboard.char53] Keyboard.Index 53
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char54"]}
scoreboard players set @e[tag=keyboard.char54] Keyboard.Index 54
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char55"]}
scoreboard players set @e[tag=keyboard.char55] Keyboard.Index 55
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char56"]}
scoreboard players set @e[tag=keyboard.char56] Keyboard.Index 56
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char57"]}
scoreboard players set @e[tag=keyboard.char57] Keyboard.Index 57
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char58"]}
scoreboard players set @e[tag=keyboard.char58] Keyboard.Index 58
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char59"]}
scoreboard players set @e[tag=keyboard.char59] Keyboard.Index 59
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char60"]}
scoreboard players set @e[tag=keyboard.char60] Keyboard.Index 60
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char61"]}
scoreboard players set @e[tag=keyboard.char61] Keyboard.Index 61
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char62"]}
scoreboard players set @e[tag=keyboard.char62] Keyboard.Index 62
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char63"]}
scoreboard players set @e[tag=keyboard.char63] Keyboard.Index 63
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char64"]}
scoreboard players set @e[tag=keyboard.char64] Keyboard.Index 64
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char65"]}
scoreboard players set @e[tag=keyboard.char65] Keyboard.Index 65
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char66"]}
scoreboard players set @e[tag=keyboard.char66] Keyboard.Index 66
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char67"]}
scoreboard players set @e[tag=keyboard.char67] Keyboard.Index 67
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char68"]}
scoreboard players set @e[tag=keyboard.char68] Keyboard.Index 68
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char69"]}
scoreboard players set @e[tag=keyboard.char69] Keyboard.Index 69
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char70"]}
scoreboard players set @e[tag=keyboard.char70] Keyboard.Index 70
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char71"]}
scoreboard players set @e[tag=keyboard.char71] Keyboard.Index 71
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char72"]}
scoreboard players set @e[tag=keyboard.char72] Keyboard.Index 72
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char73"]}
scoreboard players set @e[tag=keyboard.char73] Keyboard.Index 73
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char74"]}
scoreboard players set @e[tag=keyboard.char74] Keyboard.Index 74
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char75"]}
scoreboard players set @e[tag=keyboard.char75] Keyboard.Index 75
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char76"]}
scoreboard players set @e[tag=keyboard.char76] Keyboard.Index 76
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char77"]}
scoreboard players set @e[tag=keyboard.char77] Keyboard.Index 77
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char78"]}
scoreboard players set @e[tag=keyboard.char78] Keyboard.Index 78
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char79"]}
scoreboard players set @e[tag=keyboard.char79] Keyboard.Index 79
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char80"]}
scoreboard players set @e[tag=keyboard.char80] Keyboard.Index 80
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char81"]}
scoreboard players set @e[tag=keyboard.char81] Keyboard.Index 81
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char82"]}
scoreboard players set @e[tag=keyboard.char82] Keyboard.Index 82
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char83"]}
scoreboard players set @e[tag=keyboard.char83] Keyboard.Index 83
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char84"]}
scoreboard players set @e[tag=keyboard.char84] Keyboard.Index 84
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char85"]}
scoreboard players set @e[tag=keyboard.char85] Keyboard.Index 85
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char86"]}
scoreboard players set @e[tag=keyboard.char86] Keyboard.Index 86
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char87"]}
scoreboard players set @e[tag=keyboard.char87] Keyboard.Index 87
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char88"]}
scoreboard players set @e[tag=keyboard.char88] Keyboard.Index 88
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char89"]}
scoreboard players set @e[tag=keyboard.char89] Keyboard.Index 89
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char90"]}
scoreboard players set @e[tag=keyboard.char90] Keyboard.Index 90
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char91"]}
scoreboard players set @e[tag=keyboard.char91] Keyboard.Index 91
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char92"]}
scoreboard players set @e[tag=keyboard.char92] Keyboard.Index 92
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char93"]}
scoreboard players set @e[tag=keyboard.char93] Keyboard.Index 93
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char94"]}
scoreboard players set @e[tag=keyboard.char94] Keyboard.Index 94
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char95"]}
scoreboard players set @e[tag=keyboard.char95] Keyboard.Index 95
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char96"]}
scoreboard players set @e[tag=keyboard.char96] Keyboard.Index 96
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char97"]}
scoreboard players set @e[tag=keyboard.char97] Keyboard.Index 97
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char98"]}
scoreboard players set @e[tag=keyboard.char98] Keyboard.Index 98
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char99"]}
scoreboard players set @e[tag=keyboard.char99] Keyboard.Index 99
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char100"]}
scoreboard players set @e[tag=keyboard.char100] Keyboard.Index 100
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char101"]}
scoreboard players set @e[tag=keyboard.char101] Keyboard.Index 101
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char102"]}
scoreboard players set @e[tag=keyboard.char102] Keyboard.Index 102
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char103"]}
scoreboard players set @e[tag=keyboard.char103] Keyboard.Index 103
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char104"]}
scoreboard players set @e[tag=keyboard.char104] Keyboard.Index 104
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char105"]}
scoreboard players set @e[tag=keyboard.char105] Keyboard.Index 105
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char106"]}
scoreboard players set @e[tag=keyboard.char106] Keyboard.Index 106
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char107"]}
scoreboard players set @e[tag=keyboard.char107] Keyboard.Index 107
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char108"]}
scoreboard players set @e[tag=keyboard.char108] Keyboard.Index 108
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char109"]}
scoreboard players set @e[tag=keyboard.char109] Keyboard.Index 109
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char110"]}
scoreboard players set @e[tag=keyboard.char110] Keyboard.Index 110
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char111"]}
scoreboard players set @e[tag=keyboard.char111] Keyboard.Index 111
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char112"]}
scoreboard players set @e[tag=keyboard.char112] Keyboard.Index 112
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char113"]}
scoreboard players set @e[tag=keyboard.char113] Keyboard.Index 113
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char114"]}
scoreboard players set @e[tag=keyboard.char114] Keyboard.Index 114
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char115"]}
scoreboard players set @e[tag=keyboard.char115] Keyboard.Index 115
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char116"]}
scoreboard players set @e[tag=keyboard.char116] Keyboard.Index 116
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char117"]}
scoreboard players set @e[tag=keyboard.char117] Keyboard.Index 117
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char118"]}
scoreboard players set @e[tag=keyboard.char118] Keyboard.Index 118
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char119"]}
scoreboard players set @e[tag=keyboard.char119] Keyboard.Index 119
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char120"]}
scoreboard players set @e[tag=keyboard.char120] Keyboard.Index 120
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char121"]}
scoreboard players set @e[tag=keyboard.char121] Keyboard.Index 121
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char122"]}
scoreboard players set @e[tag=keyboard.char122] Keyboard.Index 122
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char123"]}
scoreboard players set @e[tag=keyboard.char123] Keyboard.Index 123
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char124"]}
scoreboard players set @e[tag=keyboard.char124] Keyboard.Index 124
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char125"]}
scoreboard players set @e[tag=keyboard.char125] Keyboard.Index 125
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char126"]}
scoreboard players set @e[tag=keyboard.char126] Keyboard.Index 126
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char127"]}
scoreboard players set @e[tag=keyboard.char127] Keyboard.Index 127
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char128"]}
scoreboard players set @e[tag=keyboard.char128] Keyboard.Index 128
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char129"]}
scoreboard players set @e[tag=keyboard.char129] Keyboard.Index 129
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char130"]}
scoreboard players set @e[tag=keyboard.char130] Keyboard.Index 130
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char131"]}
scoreboard players set @e[tag=keyboard.char131] Keyboard.Index 131
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char132"]}
scoreboard players set @e[tag=keyboard.char132] Keyboard.Index 132
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char133"]}
scoreboard players set @e[tag=keyboard.char133] Keyboard.Index 133
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char134"]}
scoreboard players set @e[tag=keyboard.char134] Keyboard.Index 134
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char135"]}
scoreboard players set @e[tag=keyboard.char135] Keyboard.Index 135
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char136"]}
scoreboard players set @e[tag=keyboard.char136] Keyboard.Index 136
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char137"]}
scoreboard players set @e[tag=keyboard.char137] Keyboard.Index 137
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char138"]}
scoreboard players set @e[tag=keyboard.char138] Keyboard.Index 138
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char139"]}
scoreboard players set @e[tag=keyboard.char139] Keyboard.Index 139
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char140"]}
scoreboard players set @e[tag=keyboard.char140] Keyboard.Index 140
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char141"]}
scoreboard players set @e[tag=keyboard.char141] Keyboard.Index 141
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char142"]}
scoreboard players set @e[tag=keyboard.char142] Keyboard.Index 142
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char143"]}
scoreboard players set @e[tag=keyboard.char143] Keyboard.Index 143
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char144"]}
scoreboard players set @e[tag=keyboard.char144] Keyboard.Index 144
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char145"]}
scoreboard players set @e[tag=keyboard.char145] Keyboard.Index 145
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char146"]}
scoreboard players set @e[tag=keyboard.char146] Keyboard.Index 146
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char147"]}
scoreboard players set @e[tag=keyboard.char147] Keyboard.Index 147
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char148"]}
scoreboard players set @e[tag=keyboard.char148] Keyboard.Index 148
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char149"]}
scoreboard players set @e[tag=keyboard.char149] Keyboard.Index 149
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char150"]}
scoreboard players set @e[tag=keyboard.char150] Keyboard.Index 150
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char151"]}
scoreboard players set @e[tag=keyboard.char151] Keyboard.Index 151
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char152"]}
scoreboard players set @e[tag=keyboard.char152] Keyboard.Index 152
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char153"]}
scoreboard players set @e[tag=keyboard.char153] Keyboard.Index 153
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char154"]}
scoreboard players set @e[tag=keyboard.char154] Keyboard.Index 154
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char155"]}
scoreboard players set @e[tag=keyboard.char155] Keyboard.Index 155
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char156"]}
scoreboard players set @e[tag=keyboard.char156] Keyboard.Index 156
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char157"]}
scoreboard players set @e[tag=keyboard.char157] Keyboard.Index 157
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char158"]}
scoreboard players set @e[tag=keyboard.char158] Keyboard.Index 158
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char159"]}
scoreboard players set @e[tag=keyboard.char159] Keyboard.Index 159
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char160"]}
scoreboard players set @e[tag=keyboard.char160] Keyboard.Index 160
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char161"]}
scoreboard players set @e[tag=keyboard.char161] Keyboard.Index 161
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char162"]}
scoreboard players set @e[tag=keyboard.char162] Keyboard.Index 162
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char163"]}
scoreboard players set @e[tag=keyboard.char163] Keyboard.Index 163
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char164"]}
scoreboard players set @e[tag=keyboard.char164] Keyboard.Index 164
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char165"]}
scoreboard players set @e[tag=keyboard.char165] Keyboard.Index 165
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char166"]}
scoreboard players set @e[tag=keyboard.char166] Keyboard.Index 166
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char167"]}
scoreboard players set @e[tag=keyboard.char167] Keyboard.Index 167
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char168"]}
scoreboard players set @e[tag=keyboard.char168] Keyboard.Index 168
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char169"]}
scoreboard players set @e[tag=keyboard.char169] Keyboard.Index 169
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char170"]}
scoreboard players set @e[tag=keyboard.char170] Keyboard.Index 170
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char171"]}
scoreboard players set @e[tag=keyboard.char171] Keyboard.Index 171
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char172"]}
scoreboard players set @e[tag=keyboard.char172] Keyboard.Index 172
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char173"]}
scoreboard players set @e[tag=keyboard.char173] Keyboard.Index 173
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char174"]}
scoreboard players set @e[tag=keyboard.char174] Keyboard.Index 174
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char175"]}
scoreboard players set @e[tag=keyboard.char175] Keyboard.Index 175
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char176"]}
scoreboard players set @e[tag=keyboard.char176] Keyboard.Index 176
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char177"]}
scoreboard players set @e[tag=keyboard.char177] Keyboard.Index 177
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char178"]}
scoreboard players set @e[tag=keyboard.char178] Keyboard.Index 178
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char179"]}
scoreboard players set @e[tag=keyboard.char179] Keyboard.Index 179
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char180"]}
scoreboard players set @e[tag=keyboard.char180] Keyboard.Index 180
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char181"]}
scoreboard players set @e[tag=keyboard.char181] Keyboard.Index 181
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char182"]}
scoreboard players set @e[tag=keyboard.char182] Keyboard.Index 182
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char183"]}
scoreboard players set @e[tag=keyboard.char183] Keyboard.Index 183
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char184"]}
scoreboard players set @e[tag=keyboard.char184] Keyboard.Index 184
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char185"]}
scoreboard players set @e[tag=keyboard.char185] Keyboard.Index 185
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char186"]}
scoreboard players set @e[tag=keyboard.char186] Keyboard.Index 186
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char187"]}
scoreboard players set @e[tag=keyboard.char187] Keyboard.Index 187
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char188"]}
scoreboard players set @e[tag=keyboard.char188] Keyboard.Index 188
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char189"]}
scoreboard players set @e[tag=keyboard.char189] Keyboard.Index 189
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char190"]}
scoreboard players set @e[tag=keyboard.char190] Keyboard.Index 190
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char191"]}
scoreboard players set @e[tag=keyboard.char191] Keyboard.Index 191
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char192"]}
scoreboard players set @e[tag=keyboard.char192] Keyboard.Index 192
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char193"]}
scoreboard players set @e[tag=keyboard.char193] Keyboard.Index 193
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char194"]}
scoreboard players set @e[tag=keyboard.char194] Keyboard.Index 194
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char195"]}
scoreboard players set @e[tag=keyboard.char195] Keyboard.Index 195
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char196"]}
scoreboard players set @e[tag=keyboard.char196] Keyboard.Index 196
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char197"]}
scoreboard players set @e[tag=keyboard.char197] Keyboard.Index 197
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char198"]}
scoreboard players set @e[tag=keyboard.char198] Keyboard.Index 198
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char199"]}
scoreboard players set @e[tag=keyboard.char199] Keyboard.Index 199
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char200"]}
scoreboard players set @e[tag=keyboard.char200] Keyboard.Index 200
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char201"]}
scoreboard players set @e[tag=keyboard.char201] Keyboard.Index 201
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char202"]}
scoreboard players set @e[tag=keyboard.char202] Keyboard.Index 202
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char203"]}
scoreboard players set @e[tag=keyboard.char203] Keyboard.Index 203
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char204"]}
scoreboard players set @e[tag=keyboard.char204] Keyboard.Index 204
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char205"]}
scoreboard players set @e[tag=keyboard.char205] Keyboard.Index 205
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char206"]}
scoreboard players set @e[tag=keyboard.char206] Keyboard.Index 206
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char207"]}
scoreboard players set @e[tag=keyboard.char207] Keyboard.Index 207
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char208"]}
scoreboard players set @e[tag=keyboard.char208] Keyboard.Index 208
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char209"]}
scoreboard players set @e[tag=keyboard.char209] Keyboard.Index 209
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char210"]}
scoreboard players set @e[tag=keyboard.char210] Keyboard.Index 210
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char211"]}
scoreboard players set @e[tag=keyboard.char211] Keyboard.Index 211
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char212"]}
scoreboard players set @e[tag=keyboard.char212] Keyboard.Index 212
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char213"]}
scoreboard players set @e[tag=keyboard.char213] Keyboard.Index 213
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char214"]}
scoreboard players set @e[tag=keyboard.char214] Keyboard.Index 214
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char215"]}
scoreboard players set @e[tag=keyboard.char215] Keyboard.Index 215
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char216"]}
scoreboard players set @e[tag=keyboard.char216] Keyboard.Index 216
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char217"]}
scoreboard players set @e[tag=keyboard.char217] Keyboard.Index 217
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char218"]}
scoreboard players set @e[tag=keyboard.char218] Keyboard.Index 218
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char219"]}
scoreboard players set @e[tag=keyboard.char219] Keyboard.Index 219
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char220"]}
scoreboard players set @e[tag=keyboard.char220] Keyboard.Index 220
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char221"]}
scoreboard players set @e[tag=keyboard.char221] Keyboard.Index 221
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char222"]}
scoreboard players set @e[tag=keyboard.char222] Keyboard.Index 222
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char223"]}
scoreboard players set @e[tag=keyboard.char223] Keyboard.Index 223
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char224"]}
scoreboard players set @e[tag=keyboard.char224] Keyboard.Index 224
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char225"]}
scoreboard players set @e[tag=keyboard.char225] Keyboard.Index 225
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char226"]}
scoreboard players set @e[tag=keyboard.char226] Keyboard.Index 226
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char227"]}
scoreboard players set @e[tag=keyboard.char227] Keyboard.Index 227
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char228"]}
scoreboard players set @e[tag=keyboard.char228] Keyboard.Index 228
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char229"]}
scoreboard players set @e[tag=keyboard.char229] Keyboard.Index 229
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char230"]}
scoreboard players set @e[tag=keyboard.char230] Keyboard.Index 230
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char231"]}
scoreboard players set @e[tag=keyboard.char231] Keyboard.Index 231
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char232"]}
scoreboard players set @e[tag=keyboard.char232] Keyboard.Index 232
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char233"]}
scoreboard players set @e[tag=keyboard.char233] Keyboard.Index 233
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char234"]}
scoreboard players set @e[tag=keyboard.char234] Keyboard.Index 234
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char235"]}
scoreboard players set @e[tag=keyboard.char235] Keyboard.Index 235
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char236"]}
scoreboard players set @e[tag=keyboard.char236] Keyboard.Index 236
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char237"]}
scoreboard players set @e[tag=keyboard.char237] Keyboard.Index 237
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char238"]}
scoreboard players set @e[tag=keyboard.char238] Keyboard.Index 238
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char239"]}
scoreboard players set @e[tag=keyboard.char239] Keyboard.Index 239
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char240"]}
scoreboard players set @e[tag=keyboard.char240] Keyboard.Index 240
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char241"]}
scoreboard players set @e[tag=keyboard.char241] Keyboard.Index 241
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char242"]}
scoreboard players set @e[tag=keyboard.char242] Keyboard.Index 242
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char243"]}
scoreboard players set @e[tag=keyboard.char243] Keyboard.Index 243
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char244"]}
scoreboard players set @e[tag=keyboard.char244] Keyboard.Index 244
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char245"]}
scoreboard players set @e[tag=keyboard.char245] Keyboard.Index 245
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char246"]}
scoreboard players set @e[tag=keyboard.char246] Keyboard.Index 246
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char247"]}
scoreboard players set @e[tag=keyboard.char247] Keyboard.Index 247
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char248"]}
scoreboard players set @e[tag=keyboard.char248] Keyboard.Index 248
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char249"]}
scoreboard players set @e[tag=keyboard.char249] Keyboard.Index 249
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char250"]}
scoreboard players set @e[tag=keyboard.char250] Keyboard.Index 250
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char251"]}
scoreboard players set @e[tag=keyboard.char251] Keyboard.Index 251
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char252"]}
scoreboard players set @e[tag=keyboard.char252] Keyboard.Index 252
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char253"]}
scoreboard players set @e[tag=keyboard.char253] Keyboard.Index 253
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char254"]}
scoreboard players set @e[tag=keyboard.char254] Keyboard.Index 254
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char255"]}
scoreboard players set @e[tag=keyboard.char255] Keyboard.Index 255
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char256"]}
scoreboard players set @e[tag=keyboard.char256] Keyboard.Index 256
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char257"]}
scoreboard players set @e[tag=keyboard.char257] Keyboard.Index 257
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char258"]}
scoreboard players set @e[tag=keyboard.char258] Keyboard.Index 258
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char259"]}
scoreboard players set @e[tag=keyboard.char259] Keyboard.Index 259
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char260"]}
scoreboard players set @e[tag=keyboard.char260] Keyboard.Index 260
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char261"]}
scoreboard players set @e[tag=keyboard.char261] Keyboard.Index 261
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char262"]}
scoreboard players set @e[tag=keyboard.char262] Keyboard.Index 262
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char263"]}
scoreboard players set @e[tag=keyboard.char263] Keyboard.Index 263
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char264"]}
scoreboard players set @e[tag=keyboard.char264] Keyboard.Index 264
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char265"]}
scoreboard players set @e[tag=keyboard.char265] Keyboard.Index 265
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char266"]}
scoreboard players set @e[tag=keyboard.char266] Keyboard.Index 266
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char267"]}
scoreboard players set @e[tag=keyboard.char267] Keyboard.Index 267
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char268"]}
scoreboard players set @e[tag=keyboard.char268] Keyboard.Index 268
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char269"]}
scoreboard players set @e[tag=keyboard.char269] Keyboard.Index 269
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char270"]}
scoreboard players set @e[tag=keyboard.char270] Keyboard.Index 270
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char271"]}
scoreboard players set @e[tag=keyboard.char271] Keyboard.Index 271
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char272"]}
scoreboard players set @e[tag=keyboard.char272] Keyboard.Index 272
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char273"]}
scoreboard players set @e[tag=keyboard.char273] Keyboard.Index 273
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char274"]}
scoreboard players set @e[tag=keyboard.char274] Keyboard.Index 274
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char275"]}
scoreboard players set @e[tag=keyboard.char275] Keyboard.Index 275
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char276"]}
scoreboard players set @e[tag=keyboard.char276] Keyboard.Index 276
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char277"]}
scoreboard players set @e[tag=keyboard.char277] Keyboard.Index 277
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char278"]}
scoreboard players set @e[tag=keyboard.char278] Keyboard.Index 278
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char279"]}
scoreboard players set @e[tag=keyboard.char279] Keyboard.Index 279
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char280"]}
scoreboard players set @e[tag=keyboard.char280] Keyboard.Index 280
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char281"]}
scoreboard players set @e[tag=keyboard.char281] Keyboard.Index 281
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char282"]}
scoreboard players set @e[tag=keyboard.char282] Keyboard.Index 282
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char283"]}
scoreboard players set @e[tag=keyboard.char283] Keyboard.Index 283
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char284"]}
scoreboard players set @e[tag=keyboard.char284] Keyboard.Index 284
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char285"]}
scoreboard players set @e[tag=keyboard.char285] Keyboard.Index 285
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char286"]}
scoreboard players set @e[tag=keyboard.char286] Keyboard.Index 286
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char287"]}
scoreboard players set @e[tag=keyboard.char287] Keyboard.Index 287
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char288"]}
scoreboard players set @e[tag=keyboard.char288] Keyboard.Index 288
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char289"]}
scoreboard players set @e[tag=keyboard.char289] Keyboard.Index 289
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char290"]}
scoreboard players set @e[tag=keyboard.char290] Keyboard.Index 290
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char291"]}
scoreboard players set @e[tag=keyboard.char291] Keyboard.Index 291
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char292"]}
scoreboard players set @e[tag=keyboard.char292] Keyboard.Index 292
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char293"]}
scoreboard players set @e[tag=keyboard.char293] Keyboard.Index 293
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char294"]}
scoreboard players set @e[tag=keyboard.char294] Keyboard.Index 294
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char295"]}
scoreboard players set @e[tag=keyboard.char295] Keyboard.Index 295
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char296"]}
scoreboard players set @e[tag=keyboard.char296] Keyboard.Index 296
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char297"]}
scoreboard players set @e[tag=keyboard.char297] Keyboard.Index 297
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char298"]}
scoreboard players set @e[tag=keyboard.char298] Keyboard.Index 298
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char299"]}
scoreboard players set @e[tag=keyboard.char299] Keyboard.Index 299
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char300"]}
scoreboard players set @e[tag=keyboard.char300] Keyboard.Index 300
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char301"]}
scoreboard players set @e[tag=keyboard.char301] Keyboard.Index 301
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char302"]}
scoreboard players set @e[tag=keyboard.char302] Keyboard.Index 302
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char303"]}
scoreboard players set @e[tag=keyboard.char303] Keyboard.Index 303
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char304"]}
scoreboard players set @e[tag=keyboard.char304] Keyboard.Index 304
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char305"]}
scoreboard players set @e[tag=keyboard.char305] Keyboard.Index 305
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char306"]}
scoreboard players set @e[tag=keyboard.char306] Keyboard.Index 306
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char307"]}
scoreboard players set @e[tag=keyboard.char307] Keyboard.Index 307
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char308"]}
scoreboard players set @e[tag=keyboard.char308] Keyboard.Index 308
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char309"]}
scoreboard players set @e[tag=keyboard.char309] Keyboard.Index 309
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char310"]}
scoreboard players set @e[tag=keyboard.char310] Keyboard.Index 310
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char311"]}
scoreboard players set @e[tag=keyboard.char311] Keyboard.Index 311
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char312"]}
scoreboard players set @e[tag=keyboard.char312] Keyboard.Index 312
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char313"]}
scoreboard players set @e[tag=keyboard.char313] Keyboard.Index 313
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char314"]}
scoreboard players set @e[tag=keyboard.char314] Keyboard.Index 314
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char315"]}
scoreboard players set @e[tag=keyboard.char315] Keyboard.Index 315
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char316"]}
scoreboard players set @e[tag=keyboard.char316] Keyboard.Index 316
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char317"]}
scoreboard players set @e[tag=keyboard.char317] Keyboard.Index 317
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char318"]}
scoreboard players set @e[tag=keyboard.char318] Keyboard.Index 318
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char319"]}
scoreboard players set @e[tag=keyboard.char319] Keyboard.Index 319
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char320"]}
scoreboard players set @e[tag=keyboard.char320] Keyboard.Index 320
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char321"]}
scoreboard players set @e[tag=keyboard.char321] Keyboard.Index 321
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char322"]}
scoreboard players set @e[tag=keyboard.char322] Keyboard.Index 322
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char323"]}
scoreboard players set @e[tag=keyboard.char323] Keyboard.Index 323
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char324"]}
scoreboard players set @e[tag=keyboard.char324] Keyboard.Index 324
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char325"]}
scoreboard players set @e[tag=keyboard.char325] Keyboard.Index 325
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char326"]}
scoreboard players set @e[tag=keyboard.char326] Keyboard.Index 326
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char327"]}
scoreboard players set @e[tag=keyboard.char327] Keyboard.Index 327
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char328"]}
scoreboard players set @e[tag=keyboard.char328] Keyboard.Index 328
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char329"]}
scoreboard players set @e[tag=keyboard.char329] Keyboard.Index 329
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char330"]}
scoreboard players set @e[tag=keyboard.char330] Keyboard.Index 330
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char331"]}
scoreboard players set @e[tag=keyboard.char331] Keyboard.Index 331
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char332"]}
scoreboard players set @e[tag=keyboard.char332] Keyboard.Index 332
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char333"]}
scoreboard players set @e[tag=keyboard.char333] Keyboard.Index 333
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char334"]}
scoreboard players set @e[tag=keyboard.char334] Keyboard.Index 334
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char335"]}
scoreboard players set @e[tag=keyboard.char335] Keyboard.Index 335
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char336"]}
scoreboard players set @e[tag=keyboard.char336] Keyboard.Index 336
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char337"]}
scoreboard players set @e[tag=keyboard.char337] Keyboard.Index 337
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char338"]}
scoreboard players set @e[tag=keyboard.char338] Keyboard.Index 338
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char339"]}
scoreboard players set @e[tag=keyboard.char339] Keyboard.Index 339
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char340"]}
scoreboard players set @e[tag=keyboard.char340] Keyboard.Index 340
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char341"]}
scoreboard players set @e[tag=keyboard.char341] Keyboard.Index 341
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char342"]}
scoreboard players set @e[tag=keyboard.char342] Keyboard.Index 342
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char343"]}
scoreboard players set @e[tag=keyboard.char343] Keyboard.Index 343
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char344"]}
scoreboard players set @e[tag=keyboard.char344] Keyboard.Index 344
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char345"]}
scoreboard players set @e[tag=keyboard.char345] Keyboard.Index 345
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char346"]}
scoreboard players set @e[tag=keyboard.char346] Keyboard.Index 346
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char347"]}
scoreboard players set @e[tag=keyboard.char347] Keyboard.Index 347
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char348"]}
scoreboard players set @e[tag=keyboard.char348] Keyboard.Index 348
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char349"]}
scoreboard players set @e[tag=keyboard.char349] Keyboard.Index 349
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char350"]}
scoreboard players set @e[tag=keyboard.char350] Keyboard.Index 350
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char351"]}
scoreboard players set @e[tag=keyboard.char351] Keyboard.Index 351
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char352"]}
scoreboard players set @e[tag=keyboard.char352] Keyboard.Index 352
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char353"]}
scoreboard players set @e[tag=keyboard.char353] Keyboard.Index 353
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char354"]}
scoreboard players set @e[tag=keyboard.char354] Keyboard.Index 354
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char355"]}
scoreboard players set @e[tag=keyboard.char355] Keyboard.Index 355
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char356"]}
scoreboard players set @e[tag=keyboard.char356] Keyboard.Index 356
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char357"]}
scoreboard players set @e[tag=keyboard.char357] Keyboard.Index 357
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char358"]}
scoreboard players set @e[tag=keyboard.char358] Keyboard.Index 358
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char359"]}
scoreboard players set @e[tag=keyboard.char359] Keyboard.Index 359
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char360"]}
scoreboard players set @e[tag=keyboard.char360] Keyboard.Index 360
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char361"]}
scoreboard players set @e[tag=keyboard.char361] Keyboard.Index 361
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char362"]}
scoreboard players set @e[tag=keyboard.char362] Keyboard.Index 362
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char363"]}
scoreboard players set @e[tag=keyboard.char363] Keyboard.Index 363
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char364"]}
scoreboard players set @e[tag=keyboard.char364] Keyboard.Index 364
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char365"]}
scoreboard players set @e[tag=keyboard.char365] Keyboard.Index 365
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char366"]}
scoreboard players set @e[tag=keyboard.char366] Keyboard.Index 366
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char367"]}
scoreboard players set @e[tag=keyboard.char367] Keyboard.Index 367
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char368"]}
scoreboard players set @e[tag=keyboard.char368] Keyboard.Index 368
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char369"]}
scoreboard players set @e[tag=keyboard.char369] Keyboard.Index 369
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char370"]}
scoreboard players set @e[tag=keyboard.char370] Keyboard.Index 370
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char371"]}
scoreboard players set @e[tag=keyboard.char371] Keyboard.Index 371
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char372"]}
scoreboard players set @e[tag=keyboard.char372] Keyboard.Index 372
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char373"]}
scoreboard players set @e[tag=keyboard.char373] Keyboard.Index 373
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char374"]}
scoreboard players set @e[tag=keyboard.char374] Keyboard.Index 374
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char375"]}
scoreboard players set @e[tag=keyboard.char375] Keyboard.Index 375
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char376"]}
scoreboard players set @e[tag=keyboard.char376] Keyboard.Index 376
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char377"]}
scoreboard players set @e[tag=keyboard.char377] Keyboard.Index 377
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char378"]}
scoreboard players set @e[tag=keyboard.char378] Keyboard.Index 378
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char379"]}
scoreboard players set @e[tag=keyboard.char379] Keyboard.Index 379
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char380"]}
scoreboard players set @e[tag=keyboard.char380] Keyboard.Index 380
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char381"]}
scoreboard players set @e[tag=keyboard.char381] Keyboard.Index 381
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char382"]}
scoreboard players set @e[tag=keyboard.char382] Keyboard.Index 382
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char383"]}
scoreboard players set @e[tag=keyboard.char383] Keyboard.Index 383
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char384"]}
scoreboard players set @e[tag=keyboard.char384] Keyboard.Index 384
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char385"]}
scoreboard players set @e[tag=keyboard.char385] Keyboard.Index 385
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char386"]}
scoreboard players set @e[tag=keyboard.char386] Keyboard.Index 386
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char387"]}
scoreboard players set @e[tag=keyboard.char387] Keyboard.Index 387
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char388"]}
scoreboard players set @e[tag=keyboard.char388] Keyboard.Index 388
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char389"]}
scoreboard players set @e[tag=keyboard.char389] Keyboard.Index 389
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char390"]}
scoreboard players set @e[tag=keyboard.char390] Keyboard.Index 390
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char391"]}
scoreboard players set @e[tag=keyboard.char391] Keyboard.Index 391
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char392"]}
scoreboard players set @e[tag=keyboard.char392] Keyboard.Index 392
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char393"]}
scoreboard players set @e[tag=keyboard.char393] Keyboard.Index 393
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char394"]}
scoreboard players set @e[tag=keyboard.char394] Keyboard.Index 394
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char395"]}
scoreboard players set @e[tag=keyboard.char395] Keyboard.Index 395
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char396"]}
scoreboard players set @e[tag=keyboard.char396] Keyboard.Index 396
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char397"]}
scoreboard players set @e[tag=keyboard.char397] Keyboard.Index 397
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char398"]}
scoreboard players set @e[tag=keyboard.char398] Keyboard.Index 398
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char399"]}
scoreboard players set @e[tag=keyboard.char399] Keyboard.Index 399
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char400"]}
scoreboard players set @e[tag=keyboard.char400] Keyboard.Index 400
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char401"]}
scoreboard players set @e[tag=keyboard.char401] Keyboard.Index 401
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char402"]}
scoreboard players set @e[tag=keyboard.char402] Keyboard.Index 402
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char403"]}
scoreboard players set @e[tag=keyboard.char403] Keyboard.Index 403
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char404"]}
scoreboard players set @e[tag=keyboard.char404] Keyboard.Index 404
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char405"]}
scoreboard players set @e[tag=keyboard.char405] Keyboard.Index 405
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char406"]}
scoreboard players set @e[tag=keyboard.char406] Keyboard.Index 406
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char407"]}
scoreboard players set @e[tag=keyboard.char407] Keyboard.Index 407
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char408"]}
scoreboard players set @e[tag=keyboard.char408] Keyboard.Index 408
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char409"]}
scoreboard players set @e[tag=keyboard.char409] Keyboard.Index 409
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char410"]}
scoreboard players set @e[tag=keyboard.char410] Keyboard.Index 410
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char411"]}
scoreboard players set @e[tag=keyboard.char411] Keyboard.Index 411
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char412"]}
scoreboard players set @e[tag=keyboard.char412] Keyboard.Index 412
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char413"]}
scoreboard players set @e[tag=keyboard.char413] Keyboard.Index 413
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char414"]}
scoreboard players set @e[tag=keyboard.char414] Keyboard.Index 414
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char415"]}
scoreboard players set @e[tag=keyboard.char415] Keyboard.Index 415
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char416"]}
scoreboard players set @e[tag=keyboard.char416] Keyboard.Index 416
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char417"]}
scoreboard players set @e[tag=keyboard.char417] Keyboard.Index 417
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char418"]}
scoreboard players set @e[tag=keyboard.char418] Keyboard.Index 418
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char419"]}
scoreboard players set @e[tag=keyboard.char419] Keyboard.Index 419
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char420"]}
scoreboard players set @e[tag=keyboard.char420] Keyboard.Index 420
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char421"]}
scoreboard players set @e[tag=keyboard.char421] Keyboard.Index 421
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char422"]}
scoreboard players set @e[tag=keyboard.char422] Keyboard.Index 422
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char423"]}
scoreboard players set @e[tag=keyboard.char423] Keyboard.Index 423
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char424"]}
scoreboard players set @e[tag=keyboard.char424] Keyboard.Index 424
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char425"]}
scoreboard players set @e[tag=keyboard.char425] Keyboard.Index 425
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char426"]}
scoreboard players set @e[tag=keyboard.char426] Keyboard.Index 426
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char427"]}
scoreboard players set @e[tag=keyboard.char427] Keyboard.Index 427
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char428"]}
scoreboard players set @e[tag=keyboard.char428] Keyboard.Index 428
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char429"]}
scoreboard players set @e[tag=keyboard.char429] Keyboard.Index 429
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char430"]}
scoreboard players set @e[tag=keyboard.char430] Keyboard.Index 430
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char431"]}
scoreboard players set @e[tag=keyboard.char431] Keyboard.Index 431
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char432"]}
scoreboard players set @e[tag=keyboard.char432] Keyboard.Index 432
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char433"]}
scoreboard players set @e[tag=keyboard.char433] Keyboard.Index 433
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char434"]}
scoreboard players set @e[tag=keyboard.char434] Keyboard.Index 434
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char435"]}
scoreboard players set @e[tag=keyboard.char435] Keyboard.Index 435
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char436"]}
scoreboard players set @e[tag=keyboard.char436] Keyboard.Index 436
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char437"]}
scoreboard players set @e[tag=keyboard.char437] Keyboard.Index 437
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char438"]}
scoreboard players set @e[tag=keyboard.char438] Keyboard.Index 438
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char439"]}
scoreboard players set @e[tag=keyboard.char439] Keyboard.Index 439
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char440"]}
scoreboard players set @e[tag=keyboard.char440] Keyboard.Index 440
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char441"]}
scoreboard players set @e[tag=keyboard.char441] Keyboard.Index 441
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char442"]}
scoreboard players set @e[tag=keyboard.char442] Keyboard.Index 442
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char443"]}
scoreboard players set @e[tag=keyboard.char443] Keyboard.Index 443
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char444"]}
scoreboard players set @e[tag=keyboard.char444] Keyboard.Index 444
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char445"]}
scoreboard players set @e[tag=keyboard.char445] Keyboard.Index 445
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char446"]}
scoreboard players set @e[tag=keyboard.char446] Keyboard.Index 446
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char447"]}
scoreboard players set @e[tag=keyboard.char447] Keyboard.Index 447
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char448"]}
scoreboard players set @e[tag=keyboard.char448] Keyboard.Index 448
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char449"]}
scoreboard players set @e[tag=keyboard.char449] Keyboard.Index 449
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char450"]}
scoreboard players set @e[tag=keyboard.char450] Keyboard.Index 450
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char451"]}
scoreboard players set @e[tag=keyboard.char451] Keyboard.Index 451
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char452"]}
scoreboard players set @e[tag=keyboard.char452] Keyboard.Index 452
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char453"]}
scoreboard players set @e[tag=keyboard.char453] Keyboard.Index 453
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char454"]}
scoreboard players set @e[tag=keyboard.char454] Keyboard.Index 454
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char455"]}
scoreboard players set @e[tag=keyboard.char455] Keyboard.Index 455
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char456"]}
scoreboard players set @e[tag=keyboard.char456] Keyboard.Index 456
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char457"]}
scoreboard players set @e[tag=keyboard.char457] Keyboard.Index 457
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char458"]}
scoreboard players set @e[tag=keyboard.char458] Keyboard.Index 458
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char459"]}
scoreboard players set @e[tag=keyboard.char459] Keyboard.Index 459
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char460"]}
scoreboard players set @e[tag=keyboard.char460] Keyboard.Index 460
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char461"]}
scoreboard players set @e[tag=keyboard.char461] Keyboard.Index 461
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char462"]}
scoreboard players set @e[tag=keyboard.char462] Keyboard.Index 462
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char463"]}
scoreboard players set @e[tag=keyboard.char463] Keyboard.Index 463
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char464"]}
scoreboard players set @e[tag=keyboard.char464] Keyboard.Index 464
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char465"]}
scoreboard players set @e[tag=keyboard.char465] Keyboard.Index 465
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char466"]}
scoreboard players set @e[tag=keyboard.char466] Keyboard.Index 466
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char467"]}
scoreboard players set @e[tag=keyboard.char467] Keyboard.Index 467
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char468"]}
scoreboard players set @e[tag=keyboard.char468] Keyboard.Index 468
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char469"]}
scoreboard players set @e[tag=keyboard.char469] Keyboard.Index 469
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char470"]}
scoreboard players set @e[tag=keyboard.char470] Keyboard.Index 470
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char471"]}
scoreboard players set @e[tag=keyboard.char471] Keyboard.Index 471
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char472"]}
scoreboard players set @e[tag=keyboard.char472] Keyboard.Index 472
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char473"]}
scoreboard players set @e[tag=keyboard.char473] Keyboard.Index 473
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char474"]}
scoreboard players set @e[tag=keyboard.char474] Keyboard.Index 474
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char475"]}
scoreboard players set @e[tag=keyboard.char475] Keyboard.Index 475
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char476"]}
scoreboard players set @e[tag=keyboard.char476] Keyboard.Index 476
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char477"]}
scoreboard players set @e[tag=keyboard.char477] Keyboard.Index 477
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char478"]}
scoreboard players set @e[tag=keyboard.char478] Keyboard.Index 478
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char479"]}
scoreboard players set @e[tag=keyboard.char479] Keyboard.Index 479
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char480"]}
scoreboard players set @e[tag=keyboard.char480] Keyboard.Index 480
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char481"]}
scoreboard players set @e[tag=keyboard.char481] Keyboard.Index 481
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char482"]}
scoreboard players set @e[tag=keyboard.char482] Keyboard.Index 482
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char483"]}
scoreboard players set @e[tag=keyboard.char483] Keyboard.Index 483
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char484"]}
scoreboard players set @e[tag=keyboard.char484] Keyboard.Index 484
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char485"]}
scoreboard players set @e[tag=keyboard.char485] Keyboard.Index 485
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char486"]}
scoreboard players set @e[tag=keyboard.char486] Keyboard.Index 486
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char487"]}
scoreboard players set @e[tag=keyboard.char487] Keyboard.Index 487
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char488"]}
scoreboard players set @e[tag=keyboard.char488] Keyboard.Index 488
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char489"]}
scoreboard players set @e[tag=keyboard.char489] Keyboard.Index 489
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char490"]}
scoreboard players set @e[tag=keyboard.char490] Keyboard.Index 490
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char491"]}
scoreboard players set @e[tag=keyboard.char491] Keyboard.Index 491
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char492"]}
scoreboard players set @e[tag=keyboard.char492] Keyboard.Index 492
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char493"]}
scoreboard players set @e[tag=keyboard.char493] Keyboard.Index 493
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char494"]}
scoreboard players set @e[tag=keyboard.char494] Keyboard.Index 494
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char495"]}
scoreboard players set @e[tag=keyboard.char495] Keyboard.Index 495
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char496"]}
scoreboard players set @e[tag=keyboard.char496] Keyboard.Index 496
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char497"]}
scoreboard players set @e[tag=keyboard.char497] Keyboard.Index 497
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char498"]}
scoreboard players set @e[tag=keyboard.char498] Keyboard.Index 498
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char499"]}
scoreboard players set @e[tag=keyboard.char499] Keyboard.Index 499
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char500"]}
scoreboard players set @e[tag=keyboard.char500] Keyboard.Index 500
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char501"]}
scoreboard players set @e[tag=keyboard.char501] Keyboard.Index 501
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char502"]}
scoreboard players set @e[tag=keyboard.char502] Keyboard.Index 502
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char503"]}
scoreboard players set @e[tag=keyboard.char503] Keyboard.Index 503
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char504"]}
scoreboard players set @e[tag=keyboard.char504] Keyboard.Index 504
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char505"]}
scoreboard players set @e[tag=keyboard.char505] Keyboard.Index 505
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char506"]}
scoreboard players set @e[tag=keyboard.char506] Keyboard.Index 506
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char507"]}
scoreboard players set @e[tag=keyboard.char507] Keyboard.Index 507
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char508"]}
scoreboard players set @e[tag=keyboard.char508] Keyboard.Index 508
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char509"]}
scoreboard players set @e[tag=keyboard.char509] Keyboard.Index 509
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char510"]}
scoreboard players set @e[tag=keyboard.char510] Keyboard.Index 510
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char511"]}
scoreboard players set @e[tag=keyboard.char511] Keyboard.Index 511
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char512"]}
scoreboard players set @e[tag=keyboard.char512] Keyboard.Index 512
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char513"]}
scoreboard players set @e[tag=keyboard.char513] Keyboard.Index 513
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char514"]}
scoreboard players set @e[tag=keyboard.char514] Keyboard.Index 514
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char515"]}
scoreboard players set @e[tag=keyboard.char515] Keyboard.Index 515
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char516"]}
scoreboard players set @e[tag=keyboard.char516] Keyboard.Index 516
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char517"]}
scoreboard players set @e[tag=keyboard.char517] Keyboard.Index 517
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char518"]}
scoreboard players set @e[tag=keyboard.char518] Keyboard.Index 518
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char519"]}
scoreboard players set @e[tag=keyboard.char519] Keyboard.Index 519
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char520"]}
scoreboard players set @e[tag=keyboard.char520] Keyboard.Index 520
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char521"]}
scoreboard players set @e[tag=keyboard.char521] Keyboard.Index 521
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char522"]}
scoreboard players set @e[tag=keyboard.char522] Keyboard.Index 522
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char523"]}
scoreboard players set @e[tag=keyboard.char523] Keyboard.Index 523
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char524"]}
scoreboard players set @e[tag=keyboard.char524] Keyboard.Index 524
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char525"]}
scoreboard players set @e[tag=keyboard.char525] Keyboard.Index 525
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char526"]}
scoreboard players set @e[tag=keyboard.char526] Keyboard.Index 526
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char527"]}
scoreboard players set @e[tag=keyboard.char527] Keyboard.Index 527
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char528"]}
scoreboard players set @e[tag=keyboard.char528] Keyboard.Index 528
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char529"]}
scoreboard players set @e[tag=keyboard.char529] Keyboard.Index 529
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char530"]}
scoreboard players set @e[tag=keyboard.char530] Keyboard.Index 530
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char531"]}
scoreboard players set @e[tag=keyboard.char531] Keyboard.Index 531
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char532"]}
scoreboard players set @e[tag=keyboard.char532] Keyboard.Index 532
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char533"]}
scoreboard players set @e[tag=keyboard.char533] Keyboard.Index 533
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char534"]}
scoreboard players set @e[tag=keyboard.char534] Keyboard.Index 534
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char535"]}
scoreboard players set @e[tag=keyboard.char535] Keyboard.Index 535
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char536"]}
scoreboard players set @e[tag=keyboard.char536] Keyboard.Index 536
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char537"]}
scoreboard players set @e[tag=keyboard.char537] Keyboard.Index 537
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char538"]}
scoreboard players set @e[tag=keyboard.char538] Keyboard.Index 538
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char539"]}
scoreboard players set @e[tag=keyboard.char539] Keyboard.Index 539
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char540"]}
scoreboard players set @e[tag=keyboard.char540] Keyboard.Index 540
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char541"]}
scoreboard players set @e[tag=keyboard.char541] Keyboard.Index 541
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char542"]}
scoreboard players set @e[tag=keyboard.char542] Keyboard.Index 542
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char543"]}
scoreboard players set @e[tag=keyboard.char543] Keyboard.Index 543
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char544"]}
scoreboard players set @e[tag=keyboard.char544] Keyboard.Index 544
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char545"]}
scoreboard players set @e[tag=keyboard.char545] Keyboard.Index 545
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char546"]}
scoreboard players set @e[tag=keyboard.char546] Keyboard.Index 546
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char547"]}
scoreboard players set @e[tag=keyboard.char547] Keyboard.Index 547
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char548"]}
scoreboard players set @e[tag=keyboard.char548] Keyboard.Index 548
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char549"]}
scoreboard players set @e[tag=keyboard.char549] Keyboard.Index 549
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char550"]}
scoreboard players set @e[tag=keyboard.char550] Keyboard.Index 550
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char551"]}
scoreboard players set @e[tag=keyboard.char551] Keyboard.Index 551
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char552"]}
scoreboard players set @e[tag=keyboard.char552] Keyboard.Index 552
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char553"]}
scoreboard players set @e[tag=keyboard.char553] Keyboard.Index 553
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char554"]}
scoreboard players set @e[tag=keyboard.char554] Keyboard.Index 554
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char555"]}
scoreboard players set @e[tag=keyboard.char555] Keyboard.Index 555
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char556"]}
scoreboard players set @e[tag=keyboard.char556] Keyboard.Index 556
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char557"]}
scoreboard players set @e[tag=keyboard.char557] Keyboard.Index 557
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char558"]}
scoreboard players set @e[tag=keyboard.char558] Keyboard.Index 558
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char559"]}
scoreboard players set @e[tag=keyboard.char559] Keyboard.Index 559
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char560"]}
scoreboard players set @e[tag=keyboard.char560] Keyboard.Index 560
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char561"]}
scoreboard players set @e[tag=keyboard.char561] Keyboard.Index 561
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char562"]}
scoreboard players set @e[tag=keyboard.char562] Keyboard.Index 562
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char563"]}
scoreboard players set @e[tag=keyboard.char563] Keyboard.Index 563
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char564"]}
scoreboard players set @e[tag=keyboard.char564] Keyboard.Index 564
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char565"]}
scoreboard players set @e[tag=keyboard.char565] Keyboard.Index 565
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char566"]}
scoreboard players set @e[tag=keyboard.char566] Keyboard.Index 566
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char567"]}
scoreboard players set @e[tag=keyboard.char567] Keyboard.Index 567
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char568"]}
scoreboard players set @e[tag=keyboard.char568] Keyboard.Index 568
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char569"]}
scoreboard players set @e[tag=keyboard.char569] Keyboard.Index 569
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char570"]}
scoreboard players set @e[tag=keyboard.char570] Keyboard.Index 570
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char571"]}
scoreboard players set @e[tag=keyboard.char571] Keyboard.Index 571
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char572"]}
scoreboard players set @e[tag=keyboard.char572] Keyboard.Index 572
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char573"]}
scoreboard players set @e[tag=keyboard.char573] Keyboard.Index 573
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char574"]}
scoreboard players set @e[tag=keyboard.char574] Keyboard.Index 574
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char575"]}
scoreboard players set @e[tag=keyboard.char575] Keyboard.Index 575
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char576"]}
scoreboard players set @e[tag=keyboard.char576] Keyboard.Index 576
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char577"]}
scoreboard players set @e[tag=keyboard.char577] Keyboard.Index 577
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char578"]}
scoreboard players set @e[tag=keyboard.char578] Keyboard.Index 578
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char579"]}
scoreboard players set @e[tag=keyboard.char579] Keyboard.Index 579
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char580"]}
scoreboard players set @e[tag=keyboard.char580] Keyboard.Index 580
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char581"]}
scoreboard players set @e[tag=keyboard.char581] Keyboard.Index 581
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char582"]}
scoreboard players set @e[tag=keyboard.char582] Keyboard.Index 582
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char583"]}
scoreboard players set @e[tag=keyboard.char583] Keyboard.Index 583
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char584"]}
scoreboard players set @e[tag=keyboard.char584] Keyboard.Index 584
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char585"]}
scoreboard players set @e[tag=keyboard.char585] Keyboard.Index 585
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char586"]}
scoreboard players set @e[tag=keyboard.char586] Keyboard.Index 586
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char587"]}
scoreboard players set @e[tag=keyboard.char587] Keyboard.Index 587
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char588"]}
scoreboard players set @e[tag=keyboard.char588] Keyboard.Index 588
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char589"]}
scoreboard players set @e[tag=keyboard.char589] Keyboard.Index 589
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char590"]}
scoreboard players set @e[tag=keyboard.char590] Keyboard.Index 590
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char591"]}
scoreboard players set @e[tag=keyboard.char591] Keyboard.Index 591
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char592"]}
scoreboard players set @e[tag=keyboard.char592] Keyboard.Index 592
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char593"]}
scoreboard players set @e[tag=keyboard.char593] Keyboard.Index 593
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char594"]}
scoreboard players set @e[tag=keyboard.char594] Keyboard.Index 594
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char595"]}
scoreboard players set @e[tag=keyboard.char595] Keyboard.Index 595
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char596"]}
scoreboard players set @e[tag=keyboard.char596] Keyboard.Index 596
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char597"]}
scoreboard players set @e[tag=keyboard.char597] Keyboard.Index 597
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char598"]}
scoreboard players set @e[tag=keyboard.char598] Keyboard.Index 598
summon armor_stand ~ ~ ~ {CustomName:"{\"text\":\"\"}",Tags:["Keyboard","keyboard.char599"]}
scoreboard players set @e[tag=keyboard.char599] Keyboard.Index 599
